# Distribution
dist: xenial

# Language
language: c

# Compilers
compiler:
        - clang
        - gcc

###########################Build cycle#########################################
# install apt addons (optional)
# install cache components (optional)
# before_install
# install
# before_script
# script
# before_cache (optional)
# after_success or after_failure
# before_deply (optional)
# deploy (optional)
# after_deploy (optional)
# after_script
#
#
# For C project default build cycle is : 
# install : N/A
# script : ./configure && make && make test
#

install:
- ./scripts/test.sh

script:
- ./scripts/run-test.sh

after_success:
- ./scripts/coverage.sh
-  bash <(curl -s https://codecov.io/bash)


